/**
 * Ravimoshark Contract API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: dev@ravimoshark.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type Valid = "VALID" | "INVALID" | "ALL";

export const Valid = {
    ALL: "ALL" as Valid,
    INVALID: "INVALID" as Valid,
    VALID: "VALID" as Valid
};
